# Setup
title:        BSOD Programming Team
tagline:      只有三个人的团队
baseurl:      ""
paginate:     1
locale:       "zh-CN"

# About/contact
author:
  name:       RedsXi
  url:        http://github.com/redsxi 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
